### ISSUE TITLE
undefined method `anaconda' 

### ISSUE THREAD

**Issue by xpie123** [rreben/learn-how-to-code#10]
I get an error when setting up the VM with vagrant up.

MacOS 10.12.5

==> default: Running handlers:
==> default: [2017-06-15T10:55:58+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-06-15T10:55:58+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 10 seconds
==> default: [2017-06-15T10:55:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-06-15T10:55:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-06-15T10:55:58+00:00] ERROR: undefined method `anaconda' for #<Chef::Node::VividMash:0x0000000554dd50>
==> default: [2017-06-15T10:55:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

stracktrace:
NoMethodError: undefined method `anaconda' for #<Chef::Node::VividMash:0x0000000554dd50>
/var/chef/cache/cookbooks/anaconda/attributes/default.rb:2:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/dsl/include_attribute.rb:31:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:213:in `load_attribute_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:202:in `load_attributes_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:132:in `block in compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:131:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:131:in `compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/run_context.rb:192:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/lib/chef/application/solo.rb:225:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31/bin/chef-solo:25:in `<top (required)>'

**Comment by rreben** [comment]
The chef recipes use a syntax that is no longer supported with the new versions of chef. I therefore restricted the chef version in the vagrant file. @xpie123 You would have to update your repo again (or do a new downlad).
